[package]
name = "rb_world"
version = "0.1.0"
edition = "2021"

[dependencies]
rb_core.workspace = true
rb_noise.workspace = true
bevy.workspace = true
serde.workspace = true
ron.workspace = true
pathfinding = "4.4"
rand = "0.8"
rand_chacha = "0.3"
image.workspace = true
rayon = "1.10"

[dev-dependencies]
bincode.workspace = true

[[example]]
name = "save_lifegen_layers"
path = "examples/save_lifegen_layers.rs"

[lints]
workspace = true
